# The project
PROJECT_NAME: Elsewhere
GITHUB_CURRENT_VERSION: 0.0.2
GITHUB_PROJECT_URL: https://github.com/dharmafly/elsewhere

# Site theme (options: forest, ocean, horus, seagrass, sundae, slate)
THEME: seagrass


############ Options

# URLs
GITHUB_ZIP_URL: https://github.com/dharmafly/elsewhere/zipball/master
TWITTER_PROJECT_URL: https://twitter.com/dharmafly

# Primary language or technology (options: javascript, css, html5)
LANG: javascript

# Documentation site scripts
SCRIPTS:

# Footer quote
QUOTE:
  quote: It is living and ceasing to live that are imaginary solutions. Existence is elsewhere. 
  cite: Andre Breton

# Site analytics
GA_ID: UA-34978047-3


############ Deprecated / Temporary

# Link from overview to reference
REFERENCE_LINK_TEXT: "Complete documentation can be found here:"

# Page names
# In future, new site sections will be dynamically created.
# The following paths are hard-coded to match directory names / site categories.
sections:
 - path:
   name: Overview
 - path: reference
   name: Reference


############ Jekyll options

safe:        false
auto:        false
server:      false

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   /:title
baseurl:     /

exclude: ['README.md', 'assets', 'FiddlerRules.farx']
