--- 
twitter_url: https://twitter.com/dharmafly
sections: 
- path: /index.html
  name: Overview
- path: /reference/index.html
  name: Reference
exclude: 
- README.md
- assets
- FiddlerRules.farx
ga_id: UA-34978047-3
theme: seagrass
auto: false
future: true
markdown: maruku
project_name: Elsewhere
lang: javascript
version: 0.0.4
scripts: 
- src: https://github.com/downloads/dharmafly/pablo/pablo.min.js
safe: false
pygments: false
baseurl: /
project_url: https://github.com/dharmafly/elsewhere
download_links: 
- title: Master branch zip
  subtext: v{{ version }}
  text: Elsewhere
  href: https://github.com/dharmafly/elsewhere/zipball/master
server: false
quote: 
- quote: It is living and ceasing to live that are imaginary solutions. Existence is elsewhere.
- cite: Andre Breton
permalink: /:title
lsi: false
