# The project
PROJECT_NAME: Elsewhere
GITHUB_CURRENT_VERSION: 0.0.3
GITHUB_PROJECT_URL: https://github.com/dharmafly/elsewhere

# Site theme (options: forest, ocean, horus, seagrass, sundae, slate)
THEME: seagrass


############ Options

# URLs
GITHUB_ZIP_URL: https://github.com/dharmafly/elsewhere/zipball/master
TWITTER_PROJECT_URL: https://twitter.com/dharmafly

# Primary language or technology (options: javascript, css, html5)
LANG: javascript

# Documentation site scripts
SCRIPTS:

# Footer quote
QUOTE:
  quote: It is living and ceasing to live that are imaginary solutions. Existence is elsewhere. 
  cite: Andre Breton

# Site analytics
GA_ID: UA-34978047-3

# Page names
# The following paths are hard-coded to match directory names / site categories.
sections:
 - path: /index.html
   name: Overview
 - path: /reference/index.html
   name: Reference

############ Deprecated 

# Link from overview to reference
REFERENCE_LINK_TEXT: "Complete documentation can be found here:"

############ Jekyll options

safe:        false
auto:        false
server:      false

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   /:title
baseurl:     /

exclude: ['README.md', 'assets', 'FiddlerRules.farx']
