--- 
ga_id: UA-34978047-3
THEME: seagrass
QUOTE: 
  quote: It is living and ceasing to live that are imaginary solutions. Existence is elsewhere.
  cite: Andre Breton
version: 0.0.4
download_links: 
- title: Master branch zip
  href: https://github.com/dharmafly/elsewhere/zipball/master
  subtext: v{{ version }}
  text: Elsewhere
future: true
project_name: Elsewhere
DOWNLOAD_LINKS: 
- title: Master branch zip
  href: https://github.com/dharmafly/elsewhere/zipball/master
  subtext: v{{ version }}
  text: Elsewhere
TWITTER_PROJECT_URL: https://twitter.com/dharmafly
LANG: javascript
permalink: /:title
baseurl: /
scripts: 
- src: https://github.com/downloads/dharmafly/pablo/pablo.min.js
project_url: https://github.com/dharmafly/elsewhere
theme: seagrass
quote: 
- quote: It is living and ceasing to live that are imaginary solutions. Existence is elsewhere.
- cite: Andre Breton
VERSION: 0.0.3
auto: false
GITHUB_PROJECT_URL: https://github.com/dharmafly/elsewhere
GA_ID: UA-34978047-3
markdown: maruku
twitter_url: https://twitter.com/dharmafly
SCRIPTS: 
pygments: false
lang: javascript
sections: 
- name: Overview
  path: /index.html
- name: Reference
  path: /reference/index.html
server: false
PROJECT_NAME: Elsewhere
safe: false
lsi: false
exclude: 
- README.md
- assets
- FiddlerRules.farx
