--- 
scripts: 
- src: https://github.com/downloads/dharmafly/pablo/pablo.min.js
quote: 
- quote: It is living and ceasing to live that are imaginary solutions. Existence is elsewhere.
- cite: Andre Breton
markdown: maruku
sections: 
- path: /index.html
  name: Overview
- path: /reference/index.html
  name: Reference
safe: false
server: false
baseurl: /
project_url: https://github.com/dharmafly/elsewhere
auto: false
project_name: Elsewhere
ga_id: UA-34978047-3
download_links: 
- title: Master branch zip
  subtext: v{{ version }}
  href: https://github.com/dharmafly/elsewhere/zipball/master
  text: Elsewhere
pygments: false
lang: javascript
exclude: 
- README.md
- assets
- FiddlerRules.farx
theme: seagrass
version: 0.0.4
future: true
permalink: /:title
twitter_url: https://twitter.com/dharmafly
lsi: false
